let adminData=null,adminTab='listings';
const esc=x=>{const d=document.createElement('div');d.textContent=String(x??'');return d.innerHTML};
async function af(url,options={}){const token=await authAccessToken();return fetch(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${token}`}})}
function toast(m){const e=document.getElementById('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
async function loadAdmin(){consumeOAuthHash();const token=await authAccessToken();if(!token){location.href='market.html';return}try{const r=await af('/api/admin'),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message);adminData=d;document.getElementById('adminStats').innerHTML=`<article><b>${d.stats.listings}</b><span>Хабарландыру</span></article><article><b>${d.stats.pending}</b><span>Модерацияда</span></article><article><b>${d.stats.users}</b><span>Қолданушы</span></article><article><b>${d.stats.tickets}</b><span>Ашық шағым</span></article>`;renderAdmin();}catch(e){document.getElementById('adminContent').innerHTML=`<div class="empty-note">${esc(e.message||'Рұқсат жоқ')}</div>`}}
function showAdminTab(tab,btn){adminTab=tab;document.querySelectorAll('.admin-tabs .chip').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderAdmin()}
function renderAdmin(){if(!adminData)return;const box=document.getElementById('adminContent');if(adminTab==='listings'){const all=[...adminData.listings.map(x=>({...x,kind:'listing'})),...adminData.products.map(x=>({...x,title:x.name,kind:'product'}))];box.innerHTML=all.map(x=>`<article class="admin-row"><div><span class="ticket-status ${esc(x.moderation_status)}">${esc(x.moderation_status)}</span><h3>${esc(x.title)}</h3><p>${esc(x.seller_name)} · ${esc(x.location)} · ${esc(x.price)} ₸</p></div><div class="admin-row-actions"><button class="btn btn-primary btn-small" onclick="moderate('${x.kind}','${x.id}','approved')">Мақұлдау</button><button class="btn btn-ghost btn-small" onclick="moderate('${x.kind}','${x.id}','rejected')">Қабылдамау</button></div></article>`).join('')||'<div class="empty-note">Жазба жоқ</div>';return}if(adminTab==='users'){box.innerHTML=adminData.users.map(u=>`<article class="admin-row"><div><h3>${esc(u.name)} ${u.verified?'✓':''}</h3><p>${esc(u.email||'')} · ${esc(u.phone)} · ${esc(u.role)}</p></div><div class="admin-row-actions"><button class="btn btn-ghost btn-small" onclick="updateUser('${u.auth_user_id}',${!!u.blocked},${!u.verified})">${u.verified?'Белгіні алу':'Тексерілген ету'}</button><button class="btn btn-ghost btn-small" onclick="updateUser('${u.auth_user_id}',${!u.blocked},${!!u.verified})">${u.blocked?'Бұғаттан шығару':'Бұғаттау'}</button></div></article>`).join('');return}box.innerHTML=adminData.tickets.map(t=>`<article class="admin-row"><div><span class="ticket-status ${esc(t.status)}">${esc(t.status)}</span><h3>${esc(t.subject)}</h3><p>${esc(t.category)} · ${new Date(t.created_at).toLocaleString('kk-KZ')}</p></div><a class="btn btn-ghost btn-small" href="market.html#support">Қарау</a></article>`).join('')||'<div class="empty-note">Шағым жоқ</div>'}
async function moderate(kind,id,status){const r=await af('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,id,moderation_status:status})}),d=await r.json();toast(d.ok?'Статус жаңартылды':d.message);if(d.ok)loadAdmin()}
async function updateUser(id,blocked,verified){const r=await af('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'user',id,blocked,verified})}),d=await r.json();toast(d.ok?'Қолданушы жаңартылды':d.message);if(d.ok)loadAdmin()}
loadAdmin();
