const KZ_LOCATIONS={
'Астана':['Алматы ауданы','Байқоңыр ауданы','Есіл ауданы','Нұра ауданы','Сарыарқа ауданы'],
'Алматы':['Алатау ауданы','Алмалы ауданы','Әуезов ауданы','Бостандық ауданы','Жетісу ауданы','Медеу ауданы','Наурызбай ауданы','Түрксіб ауданы'],
'Шымкент':['Абай ауданы','Әл-Фараби ауданы','Еңбекші ауданы','Қаратау ауданы','Тұран ауданы'],
'Абай':['Абай ауданы','Ақсуат ауданы','Аягөз ауданы','Бесқарағай ауданы','Бородулиха ауданы','Жарма ауданы','Көкпекті ауданы','Үржар ауданы'],
'Ақмола':['Ақкөл ауданы','Аршалы ауданы','Астрахан ауданы','Атбасар ауданы','Бурабай ауданы','Зеренді ауданы','Целиноград ауданы'],
'Ақтөбе':['Алға ауданы','Әйтеке би ауданы','Байғанин ауданы','Қарғалы ауданы','Мәртөк ауданы','Мұғалжар ауданы','Хромтау ауданы'],
'Алматы облысы':['Балқаш ауданы','Еңбекшіқазақ ауданы','Жамбыл ауданы','Іле ауданы','Қарасай ауданы','Кеген ауданы','Райымбек ауданы','Талғар ауданы','Ұйғыр ауданы'],
'Атырау':['Жылыой ауданы','Индер ауданы','Исатай ауданы','Қызылқоға ауданы','Құрманғазы ауданы','Мақат ауданы','Махамбет ауданы'],
'Батыс Қазақстан':['Ақжайық ауданы','Бәйтерек ауданы','Бөкей ордасы ауданы','Бөрілі ауданы','Жаңақала ауданы','Жәнібек ауданы','Қаратөбе ауданы','Сырым ауданы','Тасқала ауданы','Теректі ауданы'],
'Жамбыл':['Байзақ ауданы','Жамбыл ауданы','Жуалы ауданы','Қордай ауданы','Меркі ауданы','Мойынқұм ауданы','Сарысу ауданы','Талас ауданы','Тұрар Рысқұлов ауданы','Шу ауданы'],
'Жетісу':['Ақсу ауданы','Алакөл ауданы','Ескелді ауданы','Кербұлақ ауданы','Көксу ауданы','Панфилов ауданы','Сарқан ауданы'],
'Қарағанды':['Абай ауданы','Ақтоғай ауданы','Бұқар жырау ауданы','Қарқаралы ауданы','Нұра ауданы','Осакаров ауданы','Шет ауданы'],
'Қостанай':['Алтынсарин ауданы','Амангелді ауданы','Әулиекөл ауданы','Бейімбет Майлин ауданы','Денисов ауданы','Жангелдин ауданы','Қарабалық ауданы','Қостанай ауданы','Меңдіқара ауданы','Науырзым ауданы','Сарыкөл ауданы','Ұзынкөл ауданы','Федоров ауданы'],
'Қызылорда':['Арал ауданы','Жалағаш ауданы','Жаңақорған ауданы','Қазалы ауданы','Қармақшы ауданы','Сырдария ауданы','Шиелі ауданы'],
'Маңғыстау':['Бейнеу ауданы','Қарақия ауданы','Маңғыстау ауданы','Мұнайлы ауданы','Түпқараған ауданы'],
'Павлодар':['Аққулы ауданы','Ақтоғай ауданы','Баянауыл ауданы','Ертіс ауданы','Железин ауданы','Май ауданы','Павлодар ауданы','Тереңкөл ауданы','Успен ауданы','Шарбақты ауданы'],
'Солтүстік Қазақстан':['Айыртау ауданы','Ақжар ауданы','Аққайың ауданы','Есіл ауданы','Жамбыл ауданы','Қызылжар ауданы','Мамлют ауданы','Мағжан Жұмабаев ауданы','Тайынша ауданы','Тимирязев ауданы','Уәлиханов ауданы','Шал ақын ауданы'],
'Түркістан':['Бәйдібек ауданы','Жетісай ауданы','Келес ауданы','Қазығұрт ауданы','Мақтаарал ауданы','Ордабасы ауданы','Отырар ауданы','Сайрам ауданы','Сарыағаш ауданы','Сауран ауданы','Созақ ауданы','Төлеби ауданы','Түлкібас ауданы','Шардара ауданы'],
'Ұлытау':['Жаңаарқа ауданы','Ұлытау ауданы'],
'Шығыс Қазақстан':['Алтай ауданы','Глубокое ауданы','Зайсан ауданы','Катонқарағай ауданы','Күршім ауданы','Самар ауданы','Тарбағатай ауданы','Ұлан ауданы','Үлкен Нарын ауданы','Шемонаиха ауданы']};
function fillRegions(id){const e=document.getElementById(id);if(!e)return;const first=e.dataset.all||'Облысты таңдаңыз';e.innerHTML=`<option value="">${first}</option>`+Object.keys(KZ_LOCATIONS).map(x=>`<option>${x}</option>`).join('')}
function fillDistricts(regionId,districtId){const r=document.getElementById(regionId),d=document.getElementById(districtId);if(!r||!d)return;d.innerHTML='<option value="">Ауданды таңдаңыз</option>'+((KZ_LOCATIONS[r.value]||[]).map(x=>`<option>${x}</option>`).join(''));d.disabled=!r.value;syncLocation(regionId,districtId)}
function syncLocation(regionId,districtId,villageId,targetId){const r=document.getElementById(regionId),d=document.getElementById(districtId),v=villageId&&document.getElementById(villageId),t=targetId&&document.getElementById(targetId);if(t)t.value=[r?.value,d?.value,v?.value.trim()].filter(Boolean).join(', ')}
function initLocationGroup(prefix,target){fillRegions(prefix+'Region');const r=document.getElementById(prefix+'Region'),d=document.getElementById(prefix+'District'),v=document.getElementById(prefix+'Village');if(!r)return;r.addEventListener('change',()=>{fillDistricts(prefix+'Region',prefix+'District');syncLocation(prefix+'Region',prefix+'District',prefix+'Village',target)});d.addEventListener('change',()=>syncLocation(prefix+'Region',prefix+'District',prefix+'Village',target));v.addEventListener('input',()=>syncLocation(prefix+'Region',prefix+'District',prefix+'Village',target))}
function googleMapUrl(place,zoom=5){return `https://maps.google.com/maps?q=${encodeURIComponent(place+', Қазақстан')}&z=${zoom}&output=embed&hl=${document.documentElement.lang||'kk'}`}
function renderKazakhstanMap(){const box=document.getElementById('kazakhstanMap');if(!box)return;const places=Object.keys(KZ_LOCATIONS);box.innerHTML=`<div class="google-map-stage"><iframe id="googleMapFrame" title="Қазақстанның Google картасы" src="${googleMapUrl('Қазақстан',5)}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><div class="map-vignette" aria-hidden="true"></div><div class="gta-map-transition" id="gtaMapTransition" aria-hidden="true"><div class="gta-grid"></div><div class="gta-target"><i></i><span id="gtaPlaceName">ҚАЗАҚСТАН</span><small>ЖАҢА ӨҢІРГЕ АУЫСУ</small></div></div><div class="map-live-badge"><i></i> GOOGLE MAPS</div></div><div class="map-place-picker"><label for="mapPlaceSelect">Қала немесе облыс</label><select id="mapPlaceSelect" onchange="switchGoogleMap(this.value)"><option value="">Қазақстан толық картасы</option>${places.map(x=>`<option>${x}</option>`).join('')}</select><button type="button" class="btn btn-primary btn-small" onclick="switchGoogleMap(document.getElementById('mapPlaceSelect').value)">Картадан көрсету</button></div><div class="map-quick-places">${['Астана','Алматы','Шымкент','Түркістан','Қарағанды','Ақтөбе','Атырау','Өскемен'].map(x=>`<button type="button" onclick="switchGoogleMap('${x}',this)">${x}</button>`).join('')}</div>`}
let mapSwitchTimer=null;
function switchGoogleMap(place,button){place=String(place||'Қазақстан').trim()||'Қазақстан';const frame=document.getElementById('googleMapFrame'),fx=document.getElementById('gtaMapTransition');if(!frame||!fx)return;clearTimeout(mapSwitchTimer);document.querySelectorAll('.map-quick-places button').forEach(x=>x.classList.toggle('active',x===button));const select=document.getElementById('mapPlaceSelect');if(KZ_LOCATIONS[place])select.value=place;document.getElementById('gtaPlaceName').textContent=place.toUpperCase();fx.classList.remove('switching');void fx.offsetWidth;fx.classList.add('switching');mapSwitchTimer=setTimeout(()=>{frame.src=googleMapUrl(place,place==='Қазақстан'?5:9);if(KZ_LOCATIONS[place]){const filter=document.getElementById('filterRegion');filter.value=place;applyAdvancedFilters();document.getElementById('mapSelection').textContent=`Таңдалды: ${place}`}},620);setTimeout(()=>fx.classList.remove('switching'),1900)}
function selectMapRegion(region,button){switchGoogleMap(region,button)}
document.addEventListener('DOMContentLoaded',()=>{initLocationGroup('post','postLoc');initLocationGroup('prod','prodLoc');renderKazakhstanMap()});
