/* Мал Базары: чат, ұсыныс, дүкен, рейтинг, құжат, сүзгі және бронь */
let marketplaceInbox={conversations:[],messages:[],offers:[],reservations:[]},marketplaceMeId='',activeConversationId=null,chatPoll=null;
let filterLocation='',filterMin=0,filterMax=0,filterVerified=false;
const TRADE_STATUS={pending:'Күтуде',accepted:'Қабылданды',rejected:'Қабылданбады',cancelled:'Бас тартылды',completed:'Аяқталды'};
function ensureMarketplaceLogin(){if(user)return true;openModal('registerModal');showToast('Алдымен Google арқылы кіріңіз');return false;}
function toggleAdvancedFilters(){const e=document.getElementById('advancedFilters');e.hidden=!e.hidden;}
function applyAdvancedFilters(){filterLocation=document.getElementById('filterLocation').value.trim().toLowerCase();filterMin=Number(document.getElementById('filterMinPrice').value)||0;filterMax=Number(document.getElementById('filterMaxPrice').value)||0;filterVerified=document.getElementById('filterVerified').checked;renderListings();}
function resetAdvancedFilters(){['filterLocation','filterMinPrice','filterMaxPrice'].forEach(x=>document.getElementById(x).value='');document.getElementById('filterVerified').checked=false;filterLocation='';filterMin=filterMax=0;filterVerified=false;renderListings();}
async function communityFetch(mode,method='GET',body=null){const url=`/api/community?mode=${mode}`;const r=await apiFetch(url,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Әрекет орындалмады');return d;}
async function openInbox(){if(!ensureMarketplaceLogin())return;openModal('inboxModal');document.getElementById('communityContent').innerHTML='<div class="empty-note">Жүктелуде...</div>';try{marketplaceInbox=await communityFetch('inbox');marketplaceMeId=marketplaceInbox.me_id||marketplaceMeId;renderCommunity('chats');}catch(e){showToast(e.message);}}
function showCommunityTab(tab,btn){document.querySelectorAll('.community-tabs .chip').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');renderCommunity(tab);}
function renderCommunity(tab){const box=document.getElementById('communityContent');if(tab==='chats'){const items=marketplaceInbox.conversations||[];box.innerHTML=items.length?items.map(c=>{const other=c.buyer_id===marketplaceMeId?c.seller_name:c.buyer_name;const unread=(marketplaceInbox.messages||[]).filter(m=>m.conversation_id===c.id&&!m.read_at&&m.sender_id!==marketplaceMeId).length;return `<button class="community-card" onclick="openChat('${c.id}','${escapeHTML(c.listing_title)}')"><b>${escapeHTML(c.listing_title)}</b><span>${escapeHTML(other)}${unread?` · <strong>${unread} жаңа</strong>`:''}</span></button>`;}).join(''):'<div class="empty-note">Чат жоқ. Хабарландырудағы «Хат жазу» батырмасын басыңыз.</div>';return;}
 const items=tab==='offers'?marketplaceInbox.offers||[]:marketplaceInbox.reservations||[];box.innerHTML=items.length?items.map(x=>{const mine=x.buyer_id===marketplaceMeId,isPending=x.status==='pending';return `<div class="trade-card"><b>${escapeHTML(x.listing_title)}</b><span>${mine?'Сіз → сатушы':escapeHTML(x.buyer_name||'Сатып алушы')}</span>${tab==='offers'?`<strong>${Number(x.amount).toLocaleString('ru-RU')} ₸</strong>`:''}<span class="ticket-status ${escapeHTML(x.status)}">${TRADE_STATUS[x.status]||x.status}</span>${isPending?`<div class="trade-actions">${mine?`<button class="btn btn-ghost btn-small" onclick="changeTradeStatus('${tab}','${x.id}','cancelled')">Бас тарту</button>`:`<button class="btn btn-primary btn-small" onclick="changeTradeStatus('${tab}','${x.id}','accepted')">Қабылдау</button><button class="btn btn-ghost btn-small" onclick="changeTradeStatus('${tab}','${x.id}','rejected')">Қабылдамау</button>`}</div>`:''}${tab==='reservations'&&!mine&&x.status==='accepted'?`<button class="btn btn-primary btn-small" onclick="changeTradeStatus('reservations','${x.id}','completed')">Сауда аяқталды</button>`:''}</div>`;}).join(''):'<div class="empty-note">Әзірше жазба жоқ.</div>';}
async function changeTradeStatus(tab,id,status){try{await communityFetch(tab==='offers'?'offer_status':'reservation_status','PATCH',{id,status});showToast('Статус жаңартылды');await openInbox();}catch(e){showToast(e.message);}}
async function startChat(listingId){if(!ensureMarketplaceLogin())return;try{const d=await communityFetch('start_chat','POST',{listing_id:listingId});marketplaceMeId=d.me_id||marketplaceMeId;openChat(d.conversation.id,d.conversation.listing_title);}catch(e){showToast(e.message);}}
async function openChat(id,title){activeConversationId=id;document.getElementById('chatTitle').textContent=title||'Жеке чат';openModal('chatModal');await loadChat();clearInterval(chatPoll);chatPoll=setInterval(loadChat,7000);}
async function loadChat(){if(!activeConversationId)return;try{const d=await communityFetch(`messages&conversation_id=${activeConversationId}`);marketplaceMeId=d.me_id||marketplaceMeId;document.getElementById('chatMessages').innerHTML=d.messages.length?d.messages.map(m=>`<div class="chat-bubble ${m.sender_id===marketplaceMeId?'mine':''}"><b>${escapeHTML(m.sender_name)}</b><span>${escapeHTML(m.body)}</span><small>${new Date(m.created_at).toLocaleTimeString('kk-KZ',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join(''):'<div class="empty-note">Алғашқы хабарламаны жазыңыз.</div>';const b=document.getElementById('chatMessages');b.scrollTop=b.scrollHeight;}catch(e){showToast(e.message);}}
async function sendChatMessage(){const e=document.getElementById('chatInput'),message=e.value.trim();if(!message)return;try{await communityFetch('send_message','POST',{conversation_id:activeConversationId,message});e.value='';await loadChat();}catch(err){showToast(err.message);}}
function closeChat(){clearInterval(chatPoll);chatPoll=null;activeConversationId=null;closeModal('chatModal');}
async function makeOffer(id,current){if(!ensureMarketplaceLogin())return;const amount=Number(prompt(`Ұсынатын бағаңыз (қазіргі баға ${Number(current).toLocaleString('ru-RU')} ₸):`,current));if(!amount)return;try{await communityFetch('make_offer','POST',{listing_id:id,amount});showToast('Баға ұсынысы жіберілді');}catch(e){showToast(e.message);}}
async function reserveListing(id){if(!ensureMarketplaceLogin()||!confirm('Бұл малды броньға сұрайсыз ба?'))return;try{await communityFetch('reserve','POST',{listing_id:id});showToast('Бронь сұрауы сатушыға жіберілді');}catch(e){showToast(e.message);}}
async function leaveReview(id){if(!ensureMarketplaceLogin())return;const rating=Number(prompt('Баға: 1–5 жұлдыз','5')),comment=prompt('Қысқаша пікір (міндетті емес)','')||'';try{await communityFetch('review','POST',{listing_id:id,rating,comment});showToast('Пікір жарияланды');await loadListings();}catch(e){showToast(e.message);}}
async function openSeller(sellerId){if(!ensureMarketplaceLogin()||!sellerId)return;openModal('sellerModal');const box=document.getElementById('sellerProfileContent');box.innerHTML='<div class="empty-note">Жүктелуде...</div>';try{const d=await communityFetch(`seller&seller_id=${sellerId}`),s=d.seller;box.innerHTML=`<div class="seller-hero">${s.avatar_url?`<img src="${escapeHTML(s.avatar_url)}" alt="">`:'👤'}<div><h3>${escapeHTML(s.shop_name||s.name)} ${s.verified?'✓':''}</h3><p>${escapeHTML(s.name)} · ⭐ ${s.rating||'Жаңа'} (${s.review_count})</p></div></div><p>${escapeHTML(s.bio||'Сатушы өзі туралы ақпарат қоспаған.')}</p>${user?.role==='admin'?`<button class="btn btn-ghost btn-small" onclick="verifySeller('${s.auth_user_id}',${!s.verified})">${s.verified?'Белгіні алып тастау':'✓ Тексерілген ету'}</button>`:''}<h3 class="support-heading">Пікірлер</h3>${d.reviews.length?d.reviews.map(r=>`<div class="review-card"><b>${'⭐'.repeat(r.rating)} ${escapeHTML(r.reviewer_name)}</b><p>${escapeHTML(r.comment||'Пікірсіз баға')}</p></div>`).join(''):'<div class="empty-note">Әзірше пікір жоқ.</div>'}`;}catch(e){box.innerHTML=`<div class="empty-note">${escapeHTML(e.message)}</div>`;}}
async function verifySeller(seller_id,verified){try{await communityFetch('verify','PATCH',{seller_id,verified});showToast('Сатушы белгісі жаңартылды');closeModal('sellerModal');}catch(e){showToast(e.message);}}
async function saveShopProfile(){if(!ensureMarketplaceLogin())return;const shop_name=document.getElementById('shopName').value.trim(),bio=document.getElementById('shopBio').value.trim();try{const d=await communityFetch('profile','PATCH',{shop_name,bio});user.shopName=d.profile.shop_name||'';user.bio=d.profile.bio||'';showToast('Дүкен профилі сақталды');}catch(e){showToast(e.message);}}
// Профиль ашылғанда дүкен өрістерін толтыру
const originalOpenProfileModal=openProfileModal;openProfileModal=function(){originalOpenProfileModal();document.getElementById('shopName').value=user?.shopName||'';document.getElementById('shopBio').value=user?.bio||'';};
