const {requireAuth,isAdminEmail,noStore}=require('../lib/auth');
const H=e=>({apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,...e});
const root=()=>`${process.env.SUPABASE_URL}/rest/v1`;
async function data(path,options={}){const r=await fetch(root()+path,{...options,headers:H(options.headers||{})});if(!r.ok)throw new Error(await r.text());return r.status===204?[]:r.json();}
module.exports=async(req,res)=>{noStore(res);const auth=await requireAuth(req,res);if(!auth)return;try{const me=(await data(`/users?select=role&auth_user_id=eq.${auth.id}&limit=1`))[0];if(!(me?.role==='admin'||isAdminEmail(auth.email)))return res.status(403).json({ok:false,message:'Тек администратор'});
 if(req.method==='GET'){const [listings,products,users,tickets]=await Promise.all([data('/listings?select=id,title,type,location,price,seller_name,seller_phone,status,moderation_status,created_at&order=created_at.desc&limit=200'),data('/products?select=id,name,location,price,seller_name,moderation_status,created_at&order=created_at.desc&limit=100'),data('/users?select=auth_user_id,name,email,phone,role,verified,blocked,created_at&order=created_at.desc&limit=200'),data('/support_tickets?select=id,category,subject,status,created_at&order=created_at.desc&limit=100')]);return res.json({ok:true,listings,products,users,tickets,stats:{listings:listings.length,pending:listings.filter(x=>x.moderation_status==='pending').length,users:users.length,tickets:tickets.filter(x=>x.status!=='closed').length}});}
 if(req.method==='PATCH'){const kind=String(req.body?.kind||''),id=String(req.body?.id||'');if(kind==='listing'||kind==='product'){const status=String(req.body?.moderation_status||'');if(!['pending','approved','rejected'].includes(status))return res.status(400).json({ok:false,message:'Статус қате'});const table=kind==='listing'?'listings':'products',patch=kind==='listing'?{moderation_status:status,updated_at:new Date().toISOString()}:{moderation_status:status},rows=await data(`/${table}?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(patch)});return res.json({ok:true,item:rows[0]});}
 if(kind==='user'){const blocked=Boolean(req.body?.blocked),verified=Boolean(req.body?.verified);if(id===auth.id&&blocked)return res.status(400).json({ok:false,message:'Өзіңізді бұғаттай алмайсыз'});const rows=await data(`/users?auth_user_id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({blocked,verified})});return res.json({ok:true,user:rows[0]});}return res.status(400).json({ok:false,message:'Әрекет қате'});}
 return res.status(405).json({ok:false,message:'Method not allowed'});
 }catch(e){console.error('admin',e.message);return res.status(500).json({ok:false,message:'Серверде қате'});}};
